services:
  - type: web
    name: discord-presence-api
    env: python
    pythonVersion: 3.11.9
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: PORT
        value: 10000
